apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  selector:
    app: back-end-game
  ports:
  - name: game
    port: 8082
    targetPort: 8082
    nodePort: 32255
  - name: mongo
    port: 27017
    targetPort: 27017
  type: LoadBalancer