kind: StorageClass
apiVersion:  storage.k8s.io/v1
metadata:
  name: fast4
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd


---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast1
provisioner: kubernetes.io/gce-pd
parameters:
 type: pd-ssd

 