apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: display-state
spec:
  selector:
    matchLabels:
      app: frontend
  serviceName: "display-service"
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      restartPolicy: Always
      containers:
      - name: display
        image: public.ecr.aws/y3z0f7y7/display
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: claim-frontend
          mountPath: /app/*
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mongocred
                key: username
          - name: DB_PW
            valueFrom:
              secretKeyRef:
                name: mongocred
                key: password
  volumeClaimTemplates:
  - metadata:
      name: claim-frontend
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "medium"
      resources:
        requests:
          storage: 500Mi
      selector:
        matchLabels:
          type: local

---

apiVersion: v1
kind: Service
metadata:
  name: display-service
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
