apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontendpvc
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: medium