kind: PersistentVolume
apiVersion: v1
metadata:
  name: frontend
spec:
  storageClassName: medium
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/micro/frontend"

