apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-sv"
spec:
  selector:
    app: back-end-user
  ports:
  - name: user
    port: {{ .Values.user.port }}
    targetPort: {{ .Values.user.port }}
    nodePort: 32572
  - name: mongo
    port: {{ .Values.mongo.port }}
    targetPort: {{ .Values.mongo.port }}
  type: LoadBalancer