apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-state
spec:
  serviceName: "user-service"
  replicas: 2
  selector:
    matchLabels:
      app: back-end-user
  template:
    metadata:
      labels:
        app: back-end-user
    spec:
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "red"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: name
                operator: In
                values:
                - worker2
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/*
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
        - name: user
          image: public.ecr.aws/y3z0f7y7/user-authentication
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: claim-backend-user
              mountPath: /app/*
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password

  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast3"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
          cpu: 100m
          memory: 150Mi
        limits:
          storage: 2Gi
          cpu: 200m
          memory: 250Mi
      selector:
        matchLabels:
          type: fast3-user

  - metadata:
      name: claim-backend-user
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "fast2"
      resources:
        requests:
          storage: 500Mi
