apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: back-end-user
  ports:
  - name: user
    port: 8081
    targetPort: 8081
    nodePort: 32572
  - name: mongo
    port: 27017
    targetPort: 27017
  type: LoadBalancer